install: elsofeladat.cpp 
	@echo Installing elsofeladat...
	g++ -Wall -o elsofeladat elsofeladat.cpp

run:  elsofeladat
	@echo Running elsofeladat...
	./elsofeladat

clean:
	@echo Removing executables...
	rm elsofeladat
